{{-- REVIEWS SECTION --}}

@php
$reviews = [
    'review1.jpg',
    'review2.jpg',
    'review3.jpeg',
    'review4.jpg',
    'review5.jpeg',
    'review6.png',
];
@endphp
<section class="py-24 bg-pink-50">

    <div class="max-w-7xl mx-auto px-6 lg:px-10">

        {{-- HEADER --}}
        <div class="text-center mb-14">

            <div class="inline-flex items-center gap-2.5 bg-white text-pink-700 text-xs font-semibold uppercase tracking-[2.5px] px-5 py-3 rounded-full border border-pink-200 mb-5">
                <span class="w-2 h-2 bg-pink-500 rounded-full flex-shrink-0"></span>
                Customer Reviews
            </div>

            <h2 class="text-4xl lg:text-5xl font-bold text-gray-900 leading-tight tracking-tight">
                What Our <span class="text-pink-500">Clients Say</span>
            </h2>

            <p class="mt-4 text-gray-500 text-base leading-relaxed max-w-xl mx-auto">
                Real feedback from our customers who tried our products
                and shared their experience with love.
            </p>

        </div>

        {{-- SLIDER WRAPPER --}}
        <div class="relative px-8">

            {{-- LEFT BUTTON --}}
            <button
                id="rv-prev"
                aria-label="Previous reviews"
                class="absolute left-0 top-1/2 -translate-y-1/2 z-10 w-11 h-11 bg-white border border-pink-200 rounded-full flex items-center justify-center text-pink-500 shadow-sm hover:bg-pink-50 hover:border-pink-400 transition duration-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M15 19l-7-7 7-7" />
                </svg>
            </button>

            {{-- RIGHT BUTTON --}}
            <button
                id="rv-next"
                aria-label="Next reviews"
                class="absolute right-0 top-1/2 -translate-y-1/2 z-10 w-11 h-11 bg-white border border-pink-200 rounded-full flex items-center justify-center text-pink-500 shadow-sm hover:bg-pink-50 hover:border-pink-400 transition duration-200">
                <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M9 5l7 7-7 7" />
                </svg>
            </button>

            {{-- SLIDER TRACK --}}
            <div class="overflow-hidden">
                <div id="rv-slider" class="flex gap-5 transition-transform duration-500 ease-[cubic-bezier(.4,0,.2,1)]">

                    {{-- CARD --}}
                   

                               @foreach($reviews as $review)

<div class="rv-slide flex-shrink-0 w-full md:w-1/2 lg:w-1/3">

    <div class="bg-white border border-pink-100 rounded-2xl overflow-hidden flex flex-col hover:border-pink-300 hover:shadow-[0_8px_32px_rgba(236,72,153,0.1)] transition duration-300">

        <div class="w-full aspect-[4/5] bg-pink-50 overflow-hidden flex items-center justify-center">

            <img
                src="{{ asset('reviews/' . $review) }}"
                alt="Customer Review"
                loading="lazy"
                class="w-full h-full object-contain bg-white transition duration-300 hover:scale-105">

        </div>

        <div class="flex items-center justify-between px-4 py-3 border-t border-pink-50">
            <span class="text-pink-500 tracking-wide text-sm">★★★★★</span>

            <span class="inline-flex items-center gap-1 text-xs font-medium text-emerald-600">
                Verified
            </span>
        </div>

    </div>

</div>

@endforeach

                </div>
            </div>

        </div>

        {{-- DOTS --}}
        <div id="rv-dots" class="flex items-center justify-center gap-2 mt-8">
            {{-- Generated by JS --}}
        </div>

        {{-- CTA --}}
        <div class="text-center mt-14">

            <p class="text-gray-400 text-sm mb-5">
                Join hundreds of happy customers who trust our products ✨
            </p>

            <a href="#products"
               class="inline-flex items-center gap-2 bg-pink-500 hover:bg-pink-600 text-white text-sm font-semibold px-8 py-3.5 rounded-full transition duration-200 shadow-md hover:shadow-lg">
                Shop Now
                <svg xmlns="http://www.w3.org/2000/svg" class="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2.5">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                </svg>
            </a>

        </div>

    </div>

</section>

{{-- JS --}}
<script>
    (function () {
        const slider   = document.getElementById('rv-slider');
        const dotsWrap = document.getElementById('rv-dots');
        const slides   = Array.from(slider.querySelectorAll('.rv-slide'));
        const total    = slides.length;

        let idx     = 0;
        let visible = getVisible();

        function getVisible() {
            const w = window.innerWidth;
            if (w >= 1024) return 3;
            if (w >= 768)  return 2;
            return 1;
        }

        function maxIdx() {
            return Math.max(0, total - visible);
        }

        // ── build dots ────────────────────────────────────────
        function buildDots() {
            dotsWrap.innerHTML = '';
            const count = maxIdx() + 1;
            for (let i = 0; i < count; i++) {
                const d = document.createElement('button');
                d.setAttribute('aria-label', 'Go to slide ' + (i + 1));
                d.style.cssText = [
                    'height:6px',
                    'border-radius:100px',
                    'border:none',
                    'cursor:pointer',
                    'transition:all .25s',
                    'background:' + (i === 0 ? '#d4537e' : '#f4c0d1'),
                    'width:' + (i === 0 ? '20px' : '6px'),
                    'padding:0',
                ].join(';');
                d.onclick = () => goTo(i);
                dotsWrap.appendChild(d);
            }
        }

        function updateDots() {
            const dots = dotsWrap.querySelectorAll('button');
            dots.forEach((d, i) => {
                const active = i === idx;
                d.style.background = active ? '#d4537e' : '#f4c0d1';
                d.style.width      = active ? '20px'   : '6px';
            });
        }

        // ── slide width ───────────────────────────────────────
        function slideWidth() {
            if (!slides[0]) return 0;
            return slides[0].offsetWidth + 20; // 20 = gap-5
        }

        // ── go to index ───────────────────────────────────────
        function goTo(i) {
            idx = Math.max(0, Math.min(i, maxIdx()));
            slider.style.transform = 'translateX(-' + (idx * slideWidth()) + 'px)';
            updateDots();
            updateBtns();
        }

        function updateBtns() {
            document.getElementById('rv-prev').style.opacity = idx === 0        ? '0.4' : '1';
            document.getElementById('rv-next').style.opacity = idx >= maxIdx()  ? '0.4' : '1';
        }

        // ── nav buttons ───────────────────────────────────────
        document.getElementById('rv-prev').onclick = () => goTo(idx - 1);
        document.getElementById('rv-next').onclick = () => goTo(idx + 1);

        // ── touch / swipe ─────────────────────────────────────
        let touchStartX = 0;
        slider.addEventListener('touchstart', e => { touchStartX = e.touches[0].clientX; }, { passive: true });
        slider.addEventListener('touchend',   e => {
            const diff = touchStartX - e.changedTouches[0].clientX;
            if (Math.abs(diff) > 40) goTo(diff > 0 ? idx + 1 : idx - 1);
        });

        // ── responsive rebuild ────────────────────────────────
        window.addEventListener('resize', () => {
            const v = getVisible();
            if (v !== visible) {
                visible = v;
                idx = 0;
                buildDots();
                goTo(0);
            }
        });

        // ── init ──────────────────────────────────────────────
        buildDots();
        updateBtns();
    })();
</script>